### ISSUE TITLE
RangeError: Invalid code point

### ISSUE THREAD

**Issue by kaichaosun** [holochain-playground/holochain-playground#2]
When testing with [Flux application](https://github.com/juntofoundation/flux/releases/tag/v0.2.13),
```
npx @holochain-playground/cli ws://localhost:2000
```

Got following error, and the DHT entries is empty.
![image](https://user-images.githubusercontent.com/10568673/146198109-ddb34fb3-7761-4dcd-b8d9-822d5df20da6.png)

Thanks for this great tool, let me know if I can help.

**Comment by pospi** [comment]
Same issue here- the "invalid code point" messages flood the console and my "Dht Entries" panel is empty. Am getting this testing a multi-DNA, multi-zome app and connecting to tests being orchestrated via tryorama. I still seem to be able to view the full agent's source chain, but can't view the contents of any entries (only headers).

**Comment by guillemcordoba** [comment]
@kaichaosun @pospi thanks for the report, I was not handling well the case in which a Component of a Path is an object serialized with SerializedBytes. Can you try with the new version 0.0.8 and confirm this issue is fixed?

**Comment by pospi** [comment]
Working for me! Thanks for the quick fix (:

**Comment by kaichaosun** [comment]
It works perfect! 👍
